// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetHDL(arg1) {
  return window['go']['main']['App']['GetHDL'](arg1);
}

export function RepairFile(arg1, arg2) {
  return window['go']['main']['App']['RepairFile'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
