// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGame(arg1:string):Promise<main.Game>;

export function GetHDL(arg1:string):Promise<string>;

export function RepairFile(arg1:string,arg2:number):Promise<string>;

export function SelectFile():Promise<Array<main.Game>>;
